parameters:
#    return_epi_ws.example.class: ReturnEpi\WSBundle\Example

services:
#    return_epi_ws.example:
#        class: %return_epi_ws.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
